packages:
  - client
  - server

allowBuilds:
  '@scarf/scarf': true
  '@swc/core': true
  cypress: true
  esbuild: true
  unrs-resolver: true


minimumReleaseAge: 4320

overrides:
  react: ^18.2.0
  react-dom: ^18.2.0
  '@types/react': ^18.2.0
  ws: ^8.21.0
  js-yaml: ^4.2.0

peerDependencyRules:
  allowedVersions:
    react: ^18
    react-dom: ^18
    '@types/react': ^18

onlyBuiltDependencies:
  - '@scarf/scarf'
  - '@swc/core'
  - cypress
  - esbuild
  - unrs-resolver
