name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pre_job:
    # continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          skip_after_successful_duplicate: true
          concurrent_skipping: 'same_content'

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version: '24.x'
    - name: Enable pnpm
      run: npm install -g corepack@latest && corepack enable pnpm
    - name: pnpm install
      run: pnpm install --frozen-lockfile
    - name: lint
      run: pnpm run lint
    - name: build
      run: pnpm run --recursive build
    - name: test server
      run: pnpm --filter=virtual_office_server test
    - name: test client
      run: pnpm --filter=virtual-office-client test
    - name: Run cypress tests
      uses: cypress-io/github-action@v6
      with:
        start: pnpm --filter=virtual_office_server run start:e2e
